-- Rename FIXED_AMOUNT → FIXED in CommissionType enum
ALTER TYPE "CommissionType" RENAME VALUE 'FIXED_AMOUNT' TO 'FIXED';

-- Add 4 new values to CommissionBase enum
ALTER TYPE "CommissionBase" ADD VALUE IF NOT EXISTS 'BEFORE_DISCOUNT_BEFORE_TAX';
ALTER TYPE "CommissionBase" ADD VALUE IF NOT EXISTS 'AFTER_DISCOUNT_BEFORE_TAX';
ALTER TYPE "CommissionBase" ADD VALUE IF NOT EXISTS 'BEFORE_DISCOUNT_AFTER_TAX';
ALTER TYPE "CommissionBase" ADD VALUE IF NOT EXISTS 'AFTER_DISCOUNT_AFTER_TAX';
